# Generated by Django 3.2.13 on 2022-06-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likeanswer',
            old_name='question',
            new_name='answer',
        ),
        migrations.AddField(
            model_name='tag',
            name='questionsCount',
            field=models.IntegerField(null=True),
        ),
    ]
