# Generated by Django 3.2.13 on 2022-06-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220614_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='questionsCount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
